server:
  port: 81

spring:
  mvc:
    view:
      prefix: classpath:/templeates
      suffix: .html

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: -1
        min-idle: 0

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3308/blog?useUnicode=true&&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

